version: "3.9"
  
services:
  sub-service:
    image: narerv01/sub_service_image:$BUILD_NUMBER
    build:
      context: .
      dockerfile: SubService/Dockerfile 
    deploy:
      replicas: 1
      
  add-service:
    image: narerv01/add_service_image:$BUILD_NUMBER
    build:
      context: .
      dockerfile: AddService/Dockerfile 
    deploy:
      replicas: 1
      
  multiply-service:
    image: narerv01/multiply_service_image:$BUILD_NUMBER
    build:
      context: .
      dockerfile: MultiplyService/Dockerfile 
    deploy:
      replicas: 1
      
  calculator-service:
    image: narerv01/calc_service_image:$BUILD_NUMBER
    build:
      context: .
      dockerfile: Calculator/Dockerfile 
    ports:
      - "5000:80" 
      
  calchistory-service:
    image: narerv01/calchist_service_image:$BUILD_NUMBER
    build:
      context: .
      dockerfile: CalcHistoryService/Dockerfile  
      
  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      
  test-service: 
    image: narerv01/test-service_image:latest
    build:
      context: .
      dockerfile: TestService/Dockerfile
    deploy:
      replicas: 0
      
  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - featurehub-h2-data:/db
    ports:
      - 8085:8085
  app:
    build:
      context: .
      dockerfile: Calculator/Dockerfile
    depends_on:
      - featurehub
      
  seq:
    image: datalust/seq
    ports:
      - 5341:5341
      - 5342:80
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage
      
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - 3306:3306
    volumes:
      - zipkin_data:/mysql/data
      
volumes:
  rps_seq_data: 
  zipkin_data: 
  featurehub-h2-data: