# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ExamProjectAzureDocker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://examprojectnarek.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0ebff9492c441b397a613a23093cb52 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_feb44e6a7666427a868622bd7d394e5c }}

    - name: Build and push container image to registry
      uses: 1-1is0/docker-compose-build-push@publish
      with: 
        image: calculator
        tags: examprojectnarek.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0ebff9492c441b397a613a23093cb52 }}/examprojectnarek/exam-project:${{ github.sha }}
        composeFile: docker-compose.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ExamProjectAzureDocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0395277ea3b40119f15ba048ecfc8f7 }}
        images: 'examprojectnarek.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0ebff9492c441b397a613a23093cb52 }}/examprojectnarek/exam-project:${{ github.sha }}'
